/**
 * Sync API reference from the app package into the website docs.
 *
 * Reads `packages/app/docs/api-reference.md` (auto-generated by the app's
 * `bun run docs` script) and:
 *   1. Copies the full content to `src/content/docs/reference/full-api.md`
 *   2. Parses each `### \`ClassName\`` section and injects method/property
 *      tables into per-class reference pages between AUTO marker pairs.
 *
 * Marker format in reference pages:
 *   <!-- AUTO:START:ClassName:methods -->
 *   <!-- AUTO:END:ClassName:methods -->
 *
 * Usage: bun run sync-api
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..", "..");
const WEBSITE = resolve(__dirname, "..");

const SOURCE = resolve(ROOT, "packages", "app", "docs", "api-reference.md");
const DOCS_DIR = resolve(WEBSITE, "src", "content", "docs");
const FULL_API_TARGET = resolve(DOCS_DIR, "reference", "full-api.mdx");

interface ClassSection {
  name: string;
  content: string;
  properties: string[];
  methods: string[];
}

function parseApiReference(content: string): Map<string, ClassSection> {
  const sections = new Map<string, ClassSection>();
  const classRegex = /^### `(\w+)`/gm;
  const matches: Array<{ name: string; index: number }> = [];

  let match: RegExpExecArray | null;
  while ((match = classRegex.exec(content)) !== null) {
    matches.push({ name: match[1]!, index: match.index });
  }

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]!;
    const start = m.index;
    const end = i + 1 < matches.length ? matches[i + 1]!.index : content.length;
    const sectionContent = content.slice(start, end).trim();

    const properties: string[] = [];
    const methods: string[] = [];

    const propsMatch = sectionContent.match(/\*\*Properties\*\*\n\n([\s\S]*?)(?=\n\*\*|$)/);
    if (propsMatch) {
      for (const line of propsMatch[1]!.split("\n")) {
        const trimmed = line.trim();
        if (trimmed.startsWith("- `")) {
          const start = 3;
          const end = trimmed.indexOf("`", start);
          if (end > start) {
            properties.push(trimmed.slice(start, end));
          }
        }
      }
    }

    const methodsMatch = sectionContent.match(/\*\*Methods\*\*\n\n([\s\S]*?)(?=\n\*\*|$)/);
    if (methodsMatch) {
      for (const line of methodsMatch[1]!.split("\n")) {
        const trimmed = line.trim();
        if (trimmed.startsWith("- `")) {
          const sigStart = trimmed.indexOf("`") + 1;
          const sigEnd = trimmed.indexOf("`", sigStart);
          if (sigEnd > sigStart) {
            methods.push(trimmed.slice(sigStart, sigEnd));
          }
        }
      }
    }

    sections.set(m.name, {
      name: m.name,
      content: sectionContent,
      properties,
      methods,
    });
  }

  return sections;
}

function parseInterfaces(content: string): Map<string, string[]> {
  const interfaces = new Map<string, string[]>();
  const ifaceRegex = /^### `(\w+)`/gm;
  const matches: Array<{ name: string; index: number }> = [];

  let match: RegExpExecArray | null;
  while ((match = ifaceRegex.exec(content)) !== null) {
    matches.push({ name: match[1]!, index: match.index });
  }

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]!;
    const start = m.index;
    const end = i + 1 < matches.length ? matches[i + 1]!.index : content.length;
    const sectionContent = content.slice(start, end).trim();

    const propsMatch = sectionContent.match(/\*\*Properties\*\*\n\n([\s\S]*?)(?=\n\*\*|$)/);
    if (propsMatch) {
      const props: string[] = [];
      for (const line of propsMatch[1]!.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed.startsWith("- `")) continue;
        const raw = trimmed.slice(3);
        const bqEnd = raw.indexOf("`");
        if (bqEnd <= 0) continue;
        const content = raw.slice(0, bqEnd);
        if (content.startsWith("/**") || content.startsWith("*") || content.startsWith("*/"))
          continue;
        props.push(content);
      }
      if (props.length > 0) {
        interfaces.set(m.name, props);
      }
    }
  }

  return interfaces;
}

function parseTypeAliases(content: string): Map<string, string> {
  const aliases = new Map<string, string>();
  const aliasRegex = /^### `(\w+)`\n\n_Defined.*?_\n\n```typescript\n([\s\S]*?)```/gm;

  let match: RegExpExecArray | null;
  while ((match = aliasRegex.exec(content)) !== null) {
    aliases.set(match[1]!, match[2]!.trim());
  }

  return aliases;
}

function formatPropertiesTable(properties: string[]): string {
  if (properties.length === 0) return "";
  let table = "| Property | Type |\n| --- | --- |\n";
  for (const prop of properties) {
    const colonIdx = prop.indexOf(":");
    if (colonIdx > 0) {
      const name = prop.slice(0, colonIdx).trim();
      const type = prop
        .slice(colonIdx + 1)
        .trim()
        .replace(/\|/g, "\\|")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      table += `| \`${name}\` | \`${type}\` |\n`;
    } else {
      table += `| \`${prop}\` | |\n`;
    }
  }
  return table.trimEnd();
}

function formatMethodsTable(methods: string[]): string {
  if (methods.length === 0) return "";
  let table = "| Method | Signature |\n| --- | --- |\n";
  for (const method of methods) {
    const parenIdx = method.indexOf("(");
    const name = parenIdx > 0 ? method.slice(0, parenIdx).trim() : method;
    const escaped = method.replace(/\|/g, "\\|").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    table += `| \`${name}\` | \`${escaped}\` |\n`;
  }
  return table.trimEnd();
}

function injectIntoPage(filePath: string, marker: string, content: string): boolean {
  if (!existsSync(filePath)) return false;

  const fileContent = readFileSync(filePath, "utf-8");
  const startMarker = `{/* AUTO:START:${marker} */}`;
  const endMarker = `{/* AUTO:END:${marker} */}`;

  const startIdx = fileContent.indexOf(startMarker);
  const endIdx = fileContent.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1) return false;

  const before = fileContent.slice(0, startIdx + startMarker.length);
  const after = fileContent.slice(endIdx);

  const newContent = `${before}\n${content}\n${after}`;
  writeFileSync(filePath, newContent, "utf-8");
  return true;
}

function escapeMdx(content: string): string {
  return content.replace(/`([^`]+)`/g, (_match, inner: string) => {
    const escaped = inner.replace(/</g, "&lt;").replace(/>/g, "&gt;");
    return `\`${escaped}\``;
  });
}

function syncFullApi(sourceContent: string): void {
  const frontmatter = `---\ntitle: Full API Reference\ndescription: Auto-generated API reference from type declarations.\nbadge: auto\n---\n\n_This page is auto-generated from \`packages/app/docs/api-reference.md\` by \`bun run sync-api\`._\n\n`;

  const body = sourceContent.replace(/^# .*$/m, "").trim();
  const escaped = escapeMdx(body);
  writeFileSync(FULL_API_TARGET, frontmatter + escaped + "\n", "utf-8");
  console.log("  Updated reference/full-api.mdx");
}

function syncClassPages(sections: Map<string, ClassSection>): void {
  const classToPage: Record<string, string> = {
    BrowserContext: "reference/browser.mdx",
    Page: "reference/page.mdx",
    Locator: "reference/locator.mdx",
    ElementHandle: "reference/element-handle.mdx",
  };

  for (const [className, filePath] of Object.entries(classToPage)) {
    const section = sections.get(className);
    const fullPath = resolve(DOCS_DIR, filePath);
    let updated = false;

    if (section) {
      const methodsMarker = `${className}:methods`;
      const methodsTable = formatMethodsTable(section.methods);
      if (methodsTable) {
        if (injectIntoPage(fullPath, methodsMarker, methodsTable)) {
          console.log(`  Updated ${filePath} (${methodsMarker})`);
          updated = true;
        }
      }

      const propsMarker = `${className}:properties`;
      const propsTable = formatPropertiesTable(section.properties);
      if (propsTable) {
        if (injectIntoPage(fullPath, propsMarker, propsTable)) {
          console.log(`  Updated ${filePath} (${propsMarker})`);
          updated = true;
        }
      }
    }

    if (!updated) {
      console.log(`  Skipped ${filePath} (no matching markers or content)`);
    }
  }
}

function syncErrorPages(sections: Map<string, ClassSection>): void {
  const errorClasses = [
    "BunwrightError",
    "TimeoutError",
    "ElementNotFoundError",
    "SelectorError",
    "BrowserError",
  ];

  const filePath = resolve(DOCS_DIR, "reference", "errors.mdx");
  let table = "| Class | Extends | Constructor |\n| --- | --- | --- |\n";

  for (const name of errorClasses) {
    const section = sections.get(name);
    if (!section) continue;
    const extendsMatch = section.content.match(/extends\s+`?(\w+)`?/);
    const extendsName = extendsMatch ? extendsMatch[1]! : "Error";
    const ctorMatch = section.content.match(/constructor\(([^)]*)\)/);
    const ctorSig = ctorMatch ? `(${ctorMatch[1]})` : "()";
    table += `| \`${name}\` | \`${extendsName}\` | \`${ctorSig}\` |\n`;
  }

  const marker = "Errors:classes";
  if (injectIntoPage(filePath, marker, table.trimEnd())) {
    console.log("  Updated reference/errors.mdx (Errors:classes)");
  } else {
    console.log("  Skipped reference/errors.mdx (no matching marker)");
  }
}

function syncTypePages(interfaces: Map<string, string[]>, typeAliases: Map<string, string>): void {
  const filePath = resolve(DOCS_DIR, "reference", "types.mdx");

  const interfaceMarkers: Record<string, string> = {
    BrowserConfig: "BrowserConfig:interface",
    ContextOptions: "ContextOptions:interface",
    ResolvedSelector: "ResolvedSelector:interface",
  };

  for (const [ifaceName, marker] of Object.entries(interfaceMarkers)) {
    const props = interfaces.get(ifaceName);
    if (!props || props.length === 0) continue;

    let table = "| Property | Type |\n| --- | --- |\n";
    for (const prop of props) {
      const colonIdx = prop.indexOf(":");
      if (colonIdx > 0) {
        const name = prop.slice(0, colonIdx).trim();
        const type = prop
          .slice(colonIdx + 1)
          .trim()
          .replace(/\|/g, "\\|")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        table += `| \`${name}\` | \`${type}\` |\n`;
      } else {
        table += `| \`${prop}\` | |\n`;
      }
    }
    if (injectIntoPage(filePath, marker, table.trimEnd())) {
      console.log(`  Updated reference/types.mdx (${marker})`);
    }
  }

  const typeMarkers: Record<string, string> = {
    Selector: "Selector:type",
    LoadState: "LoadState:type",
  };

  for (const [typeName, marker] of Object.entries(typeMarkers)) {
    const value = typeAliases.get(typeName);
    if (!value) continue;

    const block = "```typescript\n" + value + "\n```";
    if (injectIntoPage(filePath, marker, block)) {
      console.log(`  Updated reference/types.mdx (${marker})`);
    }
  }
}

function main(): void {
  console.log("Syncing API reference...");

  if (!existsSync(SOURCE)) {
    console.error(`Source not found: ${SOURCE}`);
    console.error("Run `bun run docs` in packages/app first to generate it.");
    process.exit(1);
  }

  const sourceContent = readFileSync(SOURCE, "utf-8");

  const sections = parseApiReference(sourceContent);

  const interfacesSectionMatch = sourceContent.match(/## Interfaces\n\n([\s\S]*?)(?=\n## |$)/);
  const interfaces = interfacesSectionMatch
    ? parseInterfaces(interfacesSectionMatch[1]!)
    : new Map<string, string[]>();

  const typeAliasesSectionMatch = sourceContent.match(/## Type Aliases\n\n([\s\S]*?)(?=\n## |$)/);
  const typeAliases = typeAliasesSectionMatch
    ? parseTypeAliases(typeAliasesSectionMatch[1]!)
    : new Map<string, string>();

  syncFullApi(sourceContent);
  syncClassPages(sections);
  syncErrorPages(sections);
  syncTypePages(interfaces, typeAliases);

  console.log("Done.");
}

main();
