name: Publish Package
on:
  push:
    tags: ['v*'] # Triggers only on version tags
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run build
      - run: rm -rf src tests .npmignore bunwright.ts
      - run: bun publish --provenance # Provenance adds security verification
